### ISSUE TITLE
Supabase Auth 연동

### ISSUE THREAD

**Issue by swleeee** [swleeee/reading-record#19]
## 제목
- Supabase Auth 연동

## TODO
1. Supabase 클라이언트 생성
   - [ ] 데이터베이스와 상호 작용할 수 있는 단일 Supabase 클라이언트 생성

2. 로그인 구현
   - [ ] `signInWithPassword` 활용하여 로그인 구현

3. 회원가입 구현
   - [ ] `signUp` 활용하여 로그인 구현

4. 로그아웃 구현
   - [ ] `signOut` 활용하여 로그인 구현

## 참고사항
