### ISSUE TITLE
독서 관련 API 연동

### ISSUE THREAD

**Issue by swleeee** [swleeee/reading-record#29]
## 제목
- 독서 관련 API 연동

## TODO
1. API 연동
- [x] 도서 상세 화면 - 독서 감상 기록 생성/업데이트 연동 
- [x] 도서 상세 화면 - 특정 도서에 대한 나의 독서 감상 기록 연동
- [x] 도서 상세 화면 - 유저 독서 감상문 조회 연동 + (평점, 총 개수)
- [x] 도서 목록 화면 - 각 도서에 대한 **<ins>평점, ~~읽기상태~~</ins>** 조회 연동
       => `읽기 상태`는 임시 주석 처리
- [x] 도서 상세 화면 - 독서 감상문 좋아요 <ins>추가/취소/조회(좋아요 수, 좋아요 여부)</ins> 연동
- [x] 독서 기록 화면 - 나의 독서 리스트 조회 연동
- [x] 메인 화면 - 현재 읽고 있는 책 조회 연동
<s> 메인 화면 - 가장 인기있는 도서 조회 연동</s> **<ins>=> 추후 기능 도입 예정 (현재는 주석처리)</ins>**
- [x] 메인 화면 - 주간 독서 기록 베스트 조회 연동

2. 기능 추가
- [x] 독서 기록 변경 시 조건에 따른 토스트 문구 노출 처리
- [x] 독서 종료 날짜를 시작 날짜 이전으로 설정할 경우 에러 처리
- [x] 독서 날짜 특정 상태(ongoing, completed) 일 때 필수값 체크 및 날짜 선택 시 에러 초기화 처리
- [x] 독서 '진행 중' 상태 클릭 시 종료 날짜 선택되어 있을 경우 값 초기화 처리
- [x] Auth 관련 초기화 진행 상태 추가
       ->  로그인하지 않은 유저가 로그인이 필요한 페이지에 접근했을 경우 토스트 알림과 함께 로그인 페이지로 리다이렉트 처리
- [x] 책 추가 링크 카드 內 내용 및 링크주소(기존: /addBook, 수정: /book) 변경
- [x] 로그아웃 시 react-query 캐시 무효화 처리
- [x] 주간 베스트 감상문 카드 클릭 시 기존 링크 형태에서 모달 노출되도록 변경
- [x] 현재 읽고 있는 책 클릭 시 도서 상세페이지 이동 처리

3. 스크린 수정
- [x] 유저들의 독서 감상문 리스트 스켈레톤 UI 제작
- [x]  현재 읽고 있는 책 스켈레톤 UI 제작

4. 오류 수정
- [x] 독서 평점 초기값 오류 수정(초기 null일 때 1로 default 처리)
- [x] 독서 평점 계산 로직 수정(0, 1, 2, ... -> 1, 2, 3,...)

5. 리팩토링
- [x] 로그인한 유저가 로그인 화면에 접근했을 경우 리다이렉트 로직 수정 => 초기화 진행 상태 이용

6. 기타 수정
    1) prop 추가
   - [x] Modal => isLoading 추가
   - [x] DatePicker => hasError 추가
    2) 반복문 key 추가

7. 라이브러리 추가
   - [x] @tanstack/react-query-devtools 

 
## 참고사항
