### ISSUE TITLE
메인화면 스크린 제작

### ISSUE THREAD

**Issue by swleeee** [swleeee/reading-record#3]
## 제목
- 메인화면 스크린 제작

## TODO
1. 컴포넌트 제작 
   - [ ] Card

2. 스토리북 작성
   - [ ] Card

3. 메인화면 스크린 
   - [ ] 상단 Navbar
   - [ ] 배너 (캐러셀, 인디케이터)
   - [ ] 사람들이 많이 본 도서 리스트
   - [ ] 평점이 좋거나 사람들이 댓글을 많이 남긴 독서 감상문

## 참고사항

**Comment by swleeee** [comment]
**`Storybook`은 V1 기능 개발 완료 후 별도 학습한 후 스토리 작성**
