### ISSUE TITLE
도서 상세 스크린 수정

### ISSUE THREAD

**Issue by swleeee** [swleeee/reading-record#40]
## 제목
- 도서 상세 스크린 수정

## TODO
1. 컴포넌트 제작
   - [x] Tooltip
   - [x] ToggleButton

<br />

2. 스크린 수정
   - [x] 도서 읽기 상태 '완료' 변경 시 공개 여부에 대한 토글 버튼 적용
   - [x] 도서 상태 변경에 대한 툴팁 적용
   - [x] 도서 상세 스크린 디자인 수정 

 
## 참고사항
