### ISSUE TITLE
성능 최적화

### ISSUE THREAD

**Issue by swleeee** [swleeee/reading-record#60]
## 제목
- 성능 최적화

## TODO
1. 코드 스플리팅
    - 이유: 하나의 JS 파일로 번들링 -> 사용자가 페이지 최초 진입 시 모든 페이지에 대한 정보 불러옴 -> 초기 로딩 느리게 만듬 -> 코드 스플리팅을 이용하여 개선
    - [ ] `lazy` 함수  + `Suspense` 이용
             => 자주 이용하지 않을 것 같은 페이지 + 모달에 적용
    - [ ] `rollupOption`의 `manualChunks` 이용

2. 빌드 시 압축 적용하기
    - [ ] `vite-plugin-compression2` 라이브러리를 이용하여 압축 설정

## 참고사항
